set dotenv-load := true 

# Hiding command names with @
create day:
    @mkdir ./day-{{day}}
    @touch ./day-{{day}}/part-one.py
    @curl -s https://adventofcode.com/2015/day/{{day}}/input --cookie "session=$AOC_COOKIE" > ./day-{{day}}/input.in
    @echo "Created day-{{day}}"


dev part:
    npx nodemon --exec "clear && python part-{{part}}.py < ex.in" --ext py

solve day part:
    python ./day-{{day}}/part-{{part}}.py < ./day-{{day}}/input.in

test:
    npx nodemon --exec "clear && python test.py < ex.in" --ext py
